# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x0b\x42ookingData\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x18\n\x05\x64\x61tes\x18\x02 \x03(\x0b\x32\t.DateData\")\n\x08\x44\x61teData\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0f\n\x07movieid\x18\x02 \x03(\t\"\x0e\n\x0c\x45mptyBooking\"=\n\x0cSetBookingId\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12\x0f\n\x07movieid\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\".\n\x0b\x42ooleanData\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x98\x01\n\x07\x42ooking\x12-\n\nGetBooking\x12\r.EmptyBooking\x1a\x0c.BookingData\"\x00\x30\x01\x12+\n\x10GetBookingByUser\x12\x07.UserId\x1a\x0c.BookingData\"\x00\x12\x31\n\x10SetBookingByUser\x12\r.SetBookingId\x1a\x0c.BooleanData\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_USERID']._serialized_start=17
  _globals['_USERID']._serialized_end=37
  _globals['_BOOKINGDATA']._serialized_start=39
  _globals['_BOOKINGDATA']._serialized_end=94
  _globals['_DATEDATA']._serialized_start=96
  _globals['_DATEDATA']._serialized_end=137
  _globals['_EMPTYBOOKING']._serialized_start=139
  _globals['_EMPTYBOOKING']._serialized_end=153
  _globals['_SETBOOKINGID']._serialized_start=155
  _globals['_SETBOOKINGID']._serialized_end=216
  _globals['_BOOLEANDATA']._serialized_start=218
  _globals['_BOOLEANDATA']._serialized_end=264
  _globals['_BOOKING']._serialized_start=267
  _globals['_BOOKING']._serialized_end=419
# @@protoc_insertion_point(module_scope)
