# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import times_pb2 as times__pb2


class TimesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetShowtimes = channel.unary_stream(
                '/Times/GetShowtimes',
                request_serializer=times__pb2.Empty.SerializeToString,
                response_deserializer=times__pb2.TimesData.FromString,
                )
        self.GetShowtimesByDate = channel.unary_unary(
                '/Times/GetShowtimesByDate',
                request_serializer=times__pb2.TimesDate.SerializeToString,
                response_deserializer=times__pb2.TimesData.FromString,
                )


class TimesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetShowtimes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShowtimesByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetShowtimes': grpc.unary_stream_rpc_method_handler(
                    servicer.GetShowtimes,
                    request_deserializer=times__pb2.Empty.FromString,
                    response_serializer=times__pb2.TimesData.SerializeToString,
            ),
            'GetShowtimesByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShowtimesByDate,
                    request_deserializer=times__pb2.TimesDate.FromString,
                    response_serializer=times__pb2.TimesData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Times', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Times(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetShowtimes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Times/GetShowtimes',
            times__pb2.Empty.SerializeToString,
            times__pb2.TimesData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetShowtimesByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Times/GetShowtimesByDate',
            times__pb2.TimesDate.SerializeToString,
            times__pb2.TimesData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
